FROM python:3.9-slim

EXPOSE 8501

WORKDIR /dashboard
COPY ./dashboard .

RUN pip3 install -r requirements.txt

ENTRYPOINT ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]